# Generated by Django 6.0.5 on 2026-06-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_contacts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/images/default_product.jpg', null=True, upload_to='media/images/'),
        ),
    ]
