# Generated by Django 6.0.5 on 2026-06-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default_product.jpg', null=True, upload_to='images/'),
        ),
    ]
